server:
    port: 8081

spring:
    session:
        store-type: redis
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://47.100.219.142:5432/road_pricing
        username: road_pricing
        password: road_pricing
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 10 # 初始化连接个数
        minIdle: 50 # 连接池最小个数
        maxActive: 200 # 连接池最大个数--已过期 不在使用
        maxWait: 60000 # 获取连接等待超时的时间，单位：毫秒
        timeBetweenEvictionRunsMillis: 60000 #60s间隔
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

    redis:
        database: 0
        host: 47.100.219.142
        port: 5555
        password: igoosd.com
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 100
            max-wait: -1
        timeout: 0

    jackson:
        date-format: "yyyy-MM-dd HH:mm:ss"
        default-property-inclusion: non_null
        time-zone: GMT+8


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapping/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.igoosd.model,com.igoosd.domain
  typeEnumsPackage:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器 ---生产环节记得关闭！！！！
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    #key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#logging
logging:
  config: classpath:logback.xml

igoosd:
  server:
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCbRBDYno2kiWWTIMcBYKzg8vz3IokunP4El3ASCpTCSKxYeWod1Lv1AUeS+2rzIwxN4M/NcBTMaRc7JhrC+AwNCToh9RphQQ1kH/VQgublZY7lry0s6KxgMquPVHym/uFbdrKpMiGxdItLHKt4unIvr4BEntjQYm/AXjOBk2XbUQIDAQAB
    private-key:  MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAJtEENiejaSJZZMgxwFgrODy/PciiS6c/gSXcBIKlMJIrFh5ah3Uu/UBR5L7avMjDE3gz81wFMxpFzsmGsL4DA0JOiH1GmFBDWQf9VCC5uVljuWvLSzorGAyq49UfKb+4Vt2sqkyIbF0i0scq3i6ci+vgESe2NBib8BeM4GTZdtRAgMBAAECgYBjH0Yd9ML6atjU39UMVRqpFZdXcs3fW0xzw/ZBHk4v5lNYvFJ5ruk7ldCKzkVN6W8efMpNHiO5B9JT6ZSmKdMOsiQ7SaCfmJm2LHu7xRUQE6yVUSa/Zyaft8gY6iNzEqYlsIZCbTL/pxsABRZnZhbUMqzipKpD7zORXoQuz+cUkQJBAOcGCAE2A3o0aNvxcKzp3ljffVrqf+tLAJdSEo37YdI8usbb8H5VyBQUWWNvQE4jhZ6w6z7TgShvXmqWletlcP0CQQCsDU/2mNkY/spQoFcMKhD2pEDShoESBlDdSrZuL34aI4iOh2YoieEtWFZ3olaiWJ+w/zBxmz6QALWkgEIxQb3lAkA3polJGWTPDE7yJH/69z87c2K0Aucbm+6hhQC5OQQAa+amPpb5J9rRk3FQ9Zys9fubFY0ljjd/sQwyauHkWYRVAkAeyq8h8g8AkzEAJwINMkYg7hqP0vSslibIxANMSwGlifB5ma/l129OXz3yYUJiAbxqv/Eak+8pdIcNrsqp6BslAkBOyMWRwfezggtinWtSw25JtJyg/UYE57cTWn57UMurjozeHCrgFAawv20DV/KJ52kxhGOf8oYJMmFmkG4/irEk

oss:
  ver-picture-number: 5
  endpoint: http://47.100.219.142
  bucket:
    ver-picture:  /ver/

union:
  cusid:  990361082416001 #商户号
  appid: "00012395"
  key: allinpay123
  version: 11
  domain: https://vsp.allinpay.com/apiweb/unitorder/
  notify-url: http://47.100.219.142:8081/pay/callback #异步通知url
  #notify-url: http://193141kb26.iask.in:13496/pay/callback #异步通知url

